name: backend build and push

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  backend:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: Docker login
        run: gcloud auth configure-docker ${{ vars.REGION }}-docker.pkg.dev --quiet

      - name: Build
        run: ./build; docker images
        working-directory: backend

      - name: Push
        run: |
          docker tag redygg-backend ${{ vars.GAR }}
          docker push ${{ vars.GAR }}

      - name: Restart service
        run: gcloud run deploy redygg --image ${{ vars.GAR }}
